name: Deploy AWS Copilot App

on:
  push:
    branches:
      - main  # Deploy only on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS Copilot CLI
        run: |
          curl -Lo /tmp/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x /tmp/copilot
          sudo mv /tmp/copilot /usr/local/bin/copilot
          copilot --version  # Optional: verify installation

      - name: Deploy to AWS ECS (dev environment)
        run: |
          copilot deploy --env dev
